### ISSUE TITLE
Release Common and M&C areas API

### ISSUE THREAD

**Issue by gbonnefille** [esa/CCSDS_MO_APIS#1]
Hi,

We want to create prototype based on the Common and M&C areas. We know these standards are still in progress, but we need to produce a version before the standards are published. To do this, as we work with other teams, we need to share common official releases.

Is it possible to *release* the `API_COMMON` and `API_MC` modules? By releasing I mean using releasable Maven versions (without `-SNAPSHOT`) and setting tags on the git repositories.

I suspect we need to *release* `CCSDS_MO_XML` also.

As this is still a work in progress, perhaps versions like 0.1?

What's your feeling about this?

**Comment by SamCooper** [comment]
Done
