### ISSUE TITLE
Compiler requirement for Java 1.5 while code is using 1.6

### ISSUE THREAD

**Issue by gbonnefille** [esa/CCSDS_MO_APIS#12]
While compiling MAL_API, Eclipse complains about the usage of the annotation `@Override` while implementing an interface (Cf. Blob for example).

It appears that the usage of the annotation `@Override` in such situation was introduced in Java 1.6. But the [main parent POM](https://github.com/esa/CCSDS_MO_POM) reclaims to compile in 1.5.

I would suggest to change the main parent POM to compile in 1.6 (at least) while targeting 1.5. An other solution is to limit this change to the POM of MAL_API.

**Comment by gbonnefille** [comment]
Oups, my proposition is wrong:
- the Eclipse compiler is able to compile Java 1.6 targeting Java 1.5
- but OpenJDK doesn't.

**Comment by gbonnefille** [comment]
Oups, my report seems related to https://github.com/esa/CCSDS_MO_POM/issues/2.

**Comment by SamCooper** [comment]
Yes it has already been noted and will be fixed (by upping to requiring 1.6) in the next revision of the master POM.
